ANALYSE_ILLUST_THREADS: int = 10
WRITERAW_TO_DB_THREADS: int = 10
WRITE_TAGS_TO_DB_THREADS: int = 10
FETCH_TRANSLATED_TAG_THREADS: int = 8
WRITE_TRANSTAGS_TO_DB_THREADS: int = 10
TRANSTAG_RETURN_THREADS: int = 10
UID: str = '71963925'
COOKIE_EXPIRED_TIME = 43200